<?php
declare(strict_types=1);

use Hyva\Checkout\Model\Form\EntityFieldInterface;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magewirephp\Magewire\Component\Form as MagewireFormComponent;

/** @var Template $block */
/** @var EntityFieldInterface $field */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var MagewireFormComponent $magewire */

$field = $block->getData('field');
$form = $block->getData('form_name');
?>
<div class="block text-sm font-medium text-gray-700 <?= $field->isRequired() ? 'required' : 'not-required' ?>">
    <?= $field->getRenderer()->renderBefore($field, $form) ?>

    <div class="relative flex items-start">
        <div class="flex h-6 items-center">
            <input class="<?= $escaper->escapeHtmlAttr($field->getClass(['h-4 w-4 border-gray-300 rounded text-primary-500 cursor-pointer checked:bg-primary-500 checked:border-primary-500 checked:hover:bg-primary-500 focus:ring-primary-500 focus:ring-offset-copper-100 focus:outline-none'])) ?>"
                <?php if ($field->hasAttributes()): ?>
                    <?= /* @noEscape */
                    $field->renderAttributes() ?>
                <?php endif ?>
            />
        </div>
        <div class="ml-3 text-sm leading-6">
            <label for="<?= $escaper->escapeHtmlAttr($field->getName()) ?>" class="font-medium text-gray-900">
                <?= $escaper->escapeHtml(__($field->getLabel())) ?>
            </label>
        </div>
    </div>

    <?php if ($field->hasTooltip()): ?>
        <?= /* @noEscape */ $field->getRenderer()->renderTooltip($field) ?>
    <?php endif ?>

    <?= $field->getRenderer()->renderAfter($field, $form) ?>
</div>
